### ISSUE TITLE
Hangs on "Fetching resource list"

### ISSUE THREAD

**Issue by oscaruribe** [domaindrivendev/Swashbuckle#486]
This API totally hangs the swagger-ui.js script and I can't debug it (chrome is unresponsive).

I've validated it in the online validator without errors.

The json is here (had to rename to .txt for IIS to serve it):
http://admin40.maildirect.se/sandbox/api.txt

Any obvious errors?

**Comment by FrederikNygaardSvendsen** [comment]
I am experiencing the exact same issue here.

Installed Swashbuckle on a WebApi 2, hosted by IIS 8.5.

**Comment by ToXinE** [comment]
me too .
Installed Swashbuckle on an hybrid MVC 5 + WebApi 2, hosted by IIS 8.0

**Comment by jared-jacobson** [comment]
Yup same problem here....  MVC 5 + WebApi 2

**Comment by AndiRudi** [comment]
Me too, i've just installed it into our "big" project which contains mvc 5 and web api 2 in one solution.

**Comment by FrederikNygaardSvendsen** [comment]
Sorry for being a bit late with posting my solution for this problem.. In my case, the problem was that I used a custom JsonNegotiator. I solved the problem by using a JsonMediaTypeFormatter as part of the webapi's formatters instead. Then everything worked smoothly...

**Comment by oscaruribe** [comment]
FrederikNygaardSvendsen would you mind expanding on your solution?

**Comment by AndiRudi** [comment]
I've played a bit with my web api configuration and figured out, that it stops working when I add the following line:

**Comment by ToXinE** [comment]
@FrederikNygaardSvendsen would you mind pasting some examples of your code ?

**Comment by oscaruribe** [comment]
Turns out swagger couldn't handle circular references, had to add IgnoreDataMember to all references.

Also added a simple hack for adding oauth-password flow with username/password sent to endpoint. You can look at it here https://api.ungapped.com/swagger. Looks awesome, thank you!

Best regards

Oscar Uribe
Founder / Chief Executive Officer
oscar.uribe@ungapped.com<mailto:oscar.uribe@ungapped.com>
+46 733 526 000

[Ungapped]<http://www.ungapped.com/>
Ungapped
www.ungapped.com<http://www.ungapped.com/>
R?dmansgatan 65 | 113 60 Stockholm Sweden
Follow: Facebook<https://www.facebook.com/ungapped> | Twitter<https://twitter.com/ungapped> | LinkedIn<https://www.linkedin.com/company/ungapped> | Pinterest<https://www.pinterest.com/ungapped/>

10 dec. 2015 kl. 18:18 skrev ToXinE <notifications@github.com<mailto:notifications@github.com>>:


@FrederikNygaardSvendsen<https://github.com/FrederikNygaardSvendsen> would you mind pasting some examples of your code ?

-

**Comment by FrederikNygaardSvendsen** [comment]
Allthough it's been a while, as i recall, not using our own "custom" jsonFormatter, and setting up the formatter in the WebApiConfig this way, is what fixed the problem for me (but i dont think setting the SerializerSettings will do anything in this regard):

    public static class WebApiConfig {

        public static void Register(HttpConfiguration config) {
            var jsonFormatter = new JsonMediaTypeFormatter();

            jsonFormatter.SerializerSettings.Formatting = Formatting.Indented;
            jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            config.Formatters.Clear();
            config.Formatters.Insert(0, new GetAllPermissionsCsvFormatter());
            config.Formatters.Insert(1, jsonFormatter);

	    // ... Other stuff
        }

    }

**Comment by oscaruribe** [comment]
It was a circular reference problem. Swashbuckle ignored the [IgnoreDataMember] attributes and we got circular references. It would be a good idea to try to follow that standard☺


Best regards

Oscar Uribe
Founder / Chief Executive Officer
oscar.uribe@ungapped.com<mailto:oscar.uribe@ungapped.com> | SE: +46 733 526 000, US: +1 415 505 68 63
www.linkedin.com/in/oscaruribe<http://www.linkedin.com/in/oscaruribe>

[Ungapped]<http://www.ungapped.com/>
Ungapped | ungapped.com<https://ungapped.com/>
Rådmansgatan 65, 113 60 Stockholm Sweden | +46 8 410 413 13
180 Sansome St, San Francisco, CA 94104 | +1 800 931-6339

Follow: Facebook<https://www.facebook.com/ungapped> | Twitter<https://twitter.com/ungapped> | LinkedIn<https://www.linkedin.com/company/ungapped> | Pinterest<https://www.pinterest.com/ungapped/>

Från: Frederik Nygaard Svendsen [mailto:notifications@github.com]
Skickat: den 10 december 2015 23:27
Till: domaindrivendev/Swashbuckle <Swashbuckle@noreply.github.com>
Kopia: Oscar Uribe Enggren <oscar.uribe@ungapped.com>
Ämne: Re: [Swashbuckle] Hangs on "Fetching resource list" (#486)


Allthough it's been a while, as i recall, not using our own "custom" jsonFormatter, and setting up the formatter in the WebApiConfig this way, is what fixed the problem for me (but i dont think setting the SerializerSettings will do anything in this regard):

public static class WebApiConfig {



    public static void Register(HttpConfiguration config) {

        var jsonFormatter = new JsonMediaTypeFormatter();



        jsonFormatter.SerializerSettings.Formatting = Formatting.Indented;

        jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();



        config.Formatters.Clear();

        config.Formatters.Insert(0, new GetAllPermissionsCsvFormatter());

        config.Formatters.Insert(1, jsonFormatter);



    // ... Other stuff

    }



}

**Comment by ToXinE** [comment]
How did you solved the circular reference problem ?
I tried 
`            config.Formatters.JsonFormatter.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
            config.Formatters.JsonFormatter.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.None;`
without any success :-1:

**Comment by oscaruribe** [comment]
Turns out Swashbuckle does not use those serializer settings, they’re for web api.

I made new models for the entire web api layer instead of returning EF entities. Felt it was ugly that way anyway. Also did an Oauth sign in hack and redesign, it looks really good:

https://api.ungapped.com/swagger



Best regards

Oscar Uribe
Founder / Chief Executive Officer
oscar.uribe@ungapped.com<mailto:oscar.uribe@ungapped.com> | SE: +46 733 526 000, US: +1 415 505 68 63
www.linkedin.com/in/oscaruribe<http://www.linkedin.com/in/oscaruribe>

[Ungapped]<http://www.ungapped.com/>
Ungapped | ungapped.com<https://ungapped.com/>
Rådmansgatan 65, 113 60 Stockholm Sweden | +46 8 410 413 13
180 Sansome St, San Francisco, CA 94104 | +1 800 931-6339

Follow: Facebook<https://www.facebook.com/ungapped> | Twitter<https://twitter.com/ungapped> | LinkedIn<https://www.linkedin.com/company/ungapped> | Pinterest<https://www.pinterest.com/ungapped/>

Från: ToXinE [mailto:notifications@github.com]
Skickat: den 10 mars 2016 05:31
Till: domaindrivendev/Swashbuckle <Swashbuckle@noreply.github.com>
Kopia: Oscar Uribe Enggren <oscar.uribe@ungapped.com>
Ämne: Re: [Swashbuckle] Hangs on "Fetching resource list" (#486)


How did you solved the circular reference problem ?
I tried
config.Formatters.JsonFormatter.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
config.Formatters.JsonFormatter.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.None;
without any success [:-1:]

**Comment by domaindrivendev** [comment]
I'm going to close as it looks like this issue is resolved. Feel free to re-open if you feel there's something specific that can be done in Swashbuckle

**Comment by domaindrivendev** [comment]
Looks like there's still something to be addressed here. In general, SB should handle self-referencing types: https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Tests/Swagger/SchemaTests.cs#L389

But, I'm guessing a certain level of nesting becomes problematic. On the one hand this is probable a smell in your API design/implementation but then on the other hand SB should handle it better - at the very least detecting a critical level of nesting and throwing a meaningful exception.

Marking it for investigation

**Comment by EricSch** [comment]
any news here? My Swagger UI is still hanging, but the JSON directly is generated.

**Comment by oscaruribe** [comment]
Yes, we fixed it. In our case it was circular references from EF objects that messed it up. We ended up changing all EF objects returned into proper domain objects instead.

Poor feedback tho, and you kind of expect it too handle circular references but it doesn't.

Best regards

Oscar Uribe
Founder / Chief Executive Officer
oscar.uribe@ungapped.com<mailto:oscar.uribe@ungapped.com>
+46 733 526 000

[X]
Ungapped
www.ungapped.com<http://www.ungapped.com/>
R?dmansgatan 65 | 113 60 Stockholm Sweden
180 Sansome St | San Francisco | 94 104 CA

Follow: Facebook<https://www.facebook.com/ungapped> | Twitter<https://twitter.com/ungapped> | LinkedIn<https://www.linkedin.com/company/ungapped> | Pinterest<https://www.pinterest.com/ungapped/>

21 sep. 2016 kl. 14:24 skrev Eric Schoenholzer <notifications@github.com<mailto:notifications@github.com>>:


any news here? My Swagger UI is still hanging, but the JSON directly is generated.

-

**Comment by EricSch** [comment]
@oscaruribe Txs for your response. But are u an user or contributor here? I would like to hear from @domaindrivendev directly if they gonna fix that. 

I have no intention to change our EF, before that, I drop Swashbuckle and mark it as not usable.

**Comment by domaindrivendev** [comment]
@EricSch - what happens if you access the swagger JSON endpoint directly? Does it still hang?

**Comment by EricSch** [comment]
@domaindrivendev No, I get the JSON.

**Comment by domaindrivendev** [comment]
@EricSch - please don't drop Swashbuckle and bring my revenue numbers down. Oh wait ... I DON'T ACTUALLY GET PAID FOR THIS :)

I'm happy to try address issues but you should keep in mind that I'm providing this tool to the community with a lot of personal hours and no financial gain. Instead of complaining and calling it "unusable" you could try give something back - maybe dig in and debug the issue yourself?

Given that SB is first and foremost a Swagger generator that leverages an embedded version of the [swagger-ui](https://github.com/swagger-api/swagger-ui), we should investigate if this is a problem with the generated Swagger or a problem with the UI itself. Have you looked at the generated spec, in particular the definitions for your EF framework objects, and confirmed that it looks right?

**Comment by EricSch** [comment]
@domaindrivendev Sorry, wasn't my intention to offend you. If I would complaining, I would have written: "Fix this immediately! How you dare!" :) With "unusable" I meant only in my special case, not generally. You did a great work here, very useful.

I get the Open Source movement, but I'm also happy to pay for a product and having the corresponding support. Dig into each problem in a open source project, would be a full time job. If I find time, I contribute to projects,

So back to my problem: I will look into swagger-ui and debug the JSON.
Thanks

**Comment by benmiller86** [comment]
I am also having a problem with this. I posted all the details as a question on [stackoverflow](http://stackoverflow.com/questions/40288334/asp-net-core-web-api-swagger-docs-incorrect-with-reference-loop-between-classes) but the just of it is this:

I have 2 classes Person and Order. A Person has a list of Orders, and an Order has a single Person as navigation properties. I have a single Get method on the api that returns a list of 2 people each with 2 orders. I had to configure Json.Net to ignore the circular references to get any output from my API at all, but as it was said above Swashbuckle doesn't use this configuration. As such the example value given in the Swagger UI is displaying Person->Order->Person (person included again in each order). This isn't what is actually returned by the method.

Good news is that by adding the [JsonIgnore] attribute Order.Person fixes the issue and the Person is not included in the Order. The bad news is, I might not want to always exclude the Person from the order.

**Comment by aaronralls** [comment]
I have encountered this issue for two different reasons.

1.) I had public controller methods that I had created without the [HttpGet] attribute.
     
        [Route("{Id:int:min(1)}")]
        public  async Task<IActionResult> Get(int Id, string select = ALL_FIELDS, bool expand = false )
        { ...}
   
        Fixed with:
        [HttpGet]
        [Route("{Id:int:min(1)}")]
        public  async Task<IActionResult> Get(int Id, string select = ALL_FIELDS, bool expand = false )
        {...}
2.) When using the [FromBody] attribute in the parameter list for my Post method. 
     [HttpPost]
     public async Task<IActionResult>  Post([FromBody] TvUnit unit)
     {...}
     Note that [FromForm],[FromHeader],[FromQuery],[FromRoute] and [FromServices] doesn't cause this issue.

This is using "Swashbuckle": "6.0.0-beta902" and "Microsoft.AspNetCore.Mvc": "1.1.0"

**Comment by aaronralls** [comment]
Update: The issue doesn't occur with [FromBody] when EF objects aren't used or when using an EF object and not specifying [FromBody]

These work:
public async Task<IActionResult> Post( EF.TvUnit unit){}

public async Task<IActionResult> Post([FromBody] DomainObjet.Unit unit){}

**Comment by shyamal890** [comment]
+1

**Comment by MurtuzaTravadi** [comment]
@domaindrivendev 

i have try every solution that available online

i have try also IContentNegotiator using  this JsonContentNegotiator but its not working

**Comment by aaronralls** [comment]
@MurtuzaTravadi What is your specific issue?

**Comment by MurtuzaTravadi** [comment]
Thank you so much for such quick response @aaronralls  can you please look at #1011  and #1012

**Comment by domaindrivendev** [comment]
Closing due to inactivity. For anyone still having problems, please ensure you have the latest version. If the original issue persists, please create a new issue with clear and concise repro steps.

**Comment by TheMagnificent11** [comment]
@oscaruribe How did you work out that it was a circular reference issue?

**Comment by TheMagnificent11** [comment]
@oscaruribe How did you work that it's a circular reference issue?

**Comment by radionov** [comment]
Hello, I use your library with some modifications and I have this issue. My question is - what actually was  fixed? Because I can't found any commit related to #486 or #1205 or #918. Thank you.

**Comment by carloswm85** [comment]
I was able to solve this on my specific problem.

My best guess is that this is a problem cause by depth referencing. I had this class from Entity Framework which referenced other clases, and these classes referenced OTHER classes as well. I don't know how depth things went, but it went probably 10 or more levels down diving into classes I really was not needing. 

The solution I came up with was using a simple [DTO object](https://www.google.com/search?q=dto), and use it as a response to the Web Api query instead of REUSING that class from the EF Model. You can write by hand your DTO or use an object mapper like [AutoMapper](https://www.google.com/search?q=automapper)

I suggest a warning to be implemented in cases like this one from Swagger to the user.
